version: '3'
services:
  neural-net: 
    build: ./
    container_name: neural-net
    volumes:
      - ./neural/results:/neural/results
      - ./neural/models:/neural/models
    #  - ./neural:/neural
    #  - ./game:/game
    #  - ./tests:/tests
  # Added as part of debugging. Probably not needed
    stdin_open: true
    tty: true
  # This only works with the command docker-compose run --rm neural-net /bin/bash. Not docker-compose up. No idea why