version: '3'
services:
  neural-net: 
    build: ./
    container_name: neural-net
    volumes:
      - ./neural:/usr/neural
      - ./game:/usr/game
      - ./tests:/usr/tests
  # Added as part of debugging. Probably not needed
    stdin_open: true
    tty: true
  # This only works with the command docker-compose run --rm neural-net /bin/bash. Not docker-compose up. No idea why